//// <auto-generated />
//namespace Lecture3.Migrations
//{
//    using System.CodeDom.Compiler;
//    using System.Data.Entity.Migrations;
//    using System.Data.Entity.Migrations.Infrastructure;
//    using System.Resources;
    
//    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
//    public sealed partial class AddColumnGender : IMigrationMetadata
//    {
//        private readonly ResourceManager Resources = new ResourceManager(typeof(AddColumnGender));
        
//        string IMigrationMetadata.Id
//        {
//            get { return "202207081038582_AddColumnGender"; }
//        }
        
//        string IMigrationMetadata.Source
//        {
//            get { return null; }
//        }
        
//        string IMigrationMetadata.Target
//        {
//            get { return Resources.GetString("Target"); }
//        }
//    }
//}
